/**
 * Lucide icon mapping utility.
 * Maps MUI icon names (@mui/icons-material) and MDI icon names (mdi-material-ui)
 * to their Lucide React equivalents.
 *
 * Usage during migration:
 *   import { Trash2 } from 'lucide-react';
 * Instead of:
 *   import { Delete } from '@mui/icons-material';
 *
 * This file serves as a reference mapping for codemods and manual migration.
 */

// ── MUI @mui/icons-material → Lucide ──────────────────────────────
export const muiToLucide: Record<string, string> = {
  // Actions
  Add: 'Plus',
  AddOutlined: 'Plus',
  AddBoxOutlined: 'PlusBox',
  AddCircleOutlined: 'PlusCircle',
  AddCircleOutlineOutlined: 'PlusCircle',
  AddPhotoAlternateOutlined: 'ImagePlus',
  AddTaskOutlined: 'ListChecks',
  CancelOutlined: 'XCircle',
  ClearOutlined: 'X',
  Close: 'X',
  CloseOutlined: 'X',
  Check: 'Check',
  CheckOutlined: 'Check',
  CheckCircle: 'CheckCircle',
  CheckCircleOutlined: 'CheckCircle',
  Checklist: 'ListChecks',
  Delete: 'Trash2',
  DeleteOutlined: 'Trash2',
  DeleteOutline: 'Trash2',
  DeleteForeverOutlined: 'Trash2',
  Edit: 'Pencil',
  EditOutlined: 'Pencil',
  SaveOutlined: 'Save',
  Undo: 'Undo2',
  RestartAlt: 'RotateCcw',
  Refresh: 'RefreshCw',
  RefreshOutlined: 'RefreshCw',
  UpdateOutlined: 'RefreshCw',
  SyncOutlined: 'RefreshCw',
  SyncDisabledOutlined: 'RefreshCwOff',
  ContentCopy: 'Copy',
  ContentCopyOutlined: 'Copy',
  ContentPasteGoOutlined: 'ClipboardPaste',
  DragIndicatorOutlined: 'GripVertical',
  OpenWithOutlined: 'Move',
  TouchApp: 'Hand',

  // Navigation
  ArrowDownward: 'ArrowDown',
  ArrowUpward: 'ArrowUp',
  ArrowForward: 'ArrowRight',
  ArrowLeft: 'ArrowLeft',
  ArrowRight: 'ArrowRight',
  ArrowRightAlt: 'ArrowRight',
  ArrowRightAltOutlined: 'ArrowRight',
  ArrowDropDown: 'ChevronDown',
  ArrowDropDownOutlined: 'ChevronDown',
  ArrowDropUp: 'ChevronUp',
  ArrowDropUpOutlined: 'ChevronUp',
  ChevronRight: 'ChevronRight',
  ChevronRightOutlined: 'ChevronRight',
  KeyboardArrowDownOutlined: 'ChevronDown',
  KeyboardArrowLeft: 'ChevronLeft',
  KeyboardArrowRight: 'ChevronRight',
  KeyboardArrowRightOutlined: 'ChevronRight',
  ExpandMore: 'ChevronDown',
  ExpandMoreOutlined: 'ChevronDown',
  ExpandLess: 'ChevronUp',
  ExpandLessOutlined: 'ChevronUp',
  DoubleArrow: 'ChevronsRight',
  NorthEastOutlined: 'ArrowUpRight',

  // Visibility
  Visibility: 'Eye',
  VisibilityOutlined: 'Eye',
  VisibilityOff: 'EyeOff',
  VisibilityOffOutlined: 'EyeOff',
  ZoomInOutlined: 'ZoomIn',
  ZoomOutOutlined: 'ZoomOut',
  ZoomOutMapOutlined: 'Maximize',
  FullscreenOutlined: 'Maximize',
  AspectRatioOutlined: 'Maximize2',

  // People & accounts
  Person: 'User',
  PersonOutlined: 'User',
  AccountCircleOutlined: 'CircleUser',
  GroupOutlined: 'Users',
  ManageAccountsOutlined: 'UserCog',
  LockPersonOutlined: 'UserLock',
  LoginOutlined: 'LogIn',

  // Settings & admin
  SettingsOutlined: 'Settings',
  SettingsSuggestOutlined: 'Settings2',
  AdminPanelSettingsOutlined: 'ShieldCheck',
  TuneOutlined: 'SlidersHorizontal',
  PaletteOutlined: 'Palette',
  ManageHistoryOutlined: 'History',
  ManageSearchOutlined: 'SearchCheck',

  // Files & documents
  FileDownloadOutlined: 'Download',
  FileUploadOutlined: 'Upload',
  FileOpenOutlined: 'FileOpen',
  UploadFileOutlined: 'FileUp',
  CloudUploadOutlined: 'CloudUpload',
  DownloadingOutlined: 'DownloadCloud',
  GetAppOutlined: 'Download',
  FolderOutlined: 'Folder',
  DescriptionOutlined: 'FileText',
  DocumentScannerOutlined: 'FileScan',
  LibraryBooksOutlined: 'Library',
  SourceOutlined: 'FileCode',
  FileOpenOutlined: 'FileOpen',
  MoveToInboxOutlined: 'Inbox',

  // Search & filter
  Search: 'Search',
  FilterListOutlined: 'Filter',
  FilterListOffOutlined: 'FilterX',
  FilterAltOffOutlined: 'FilterX',

  // Info & status
  InfoOutlined: 'Info',
  HelpOutlined: 'HelpCircle',
  Warning: 'AlertTriangle',
  WarningOutlined: 'AlertTriangle',
  WarningAmber: 'AlertTriangle',
  WarningAmberOutlined: 'AlertTriangle',
  ErrorOutline: 'AlertCircle',
  ErrorOutlined: 'AlertCircle',
  ReportGmailerrorred: 'AlertCircle',
  NotificationsOutlined: 'Bell',
  MessageOutlined: 'MessageSquare',

  // Security
  Security: 'Shield',
  ShieldOutlined: 'Shield',
  NoEncryptionOutlined: 'ShieldOff',
  LockOutlined: 'Lock',
  LockOpenOutlined: 'LockOpen',
  KeyOutlined: 'Key',
  VerifiedOutlined: 'BadgeCheck',
  FactCheckOutlined: 'ClipboardCheck',

  // Communication
  SendOutlined: 'Send',
  CampaignOutlined: 'Megaphone',
  CommentOutlined: 'MessageSquare',
  RateReviewOutlined: 'MessageSquarePen',
  PostOutlined: 'FileText',

  // Charts & data
  InsertChartOutlined: 'BarChart3',
  PieChartOutlined: 'PieChart',
  ScatterPlotOutlined: 'ScatterChart',
  StorageOutlined: 'Database',
  DataObjectOutlined: 'Braces',
  NumbersOutlined: 'Hash',
  Database: 'Database',

  // Development
  HtmlOutlined: 'Code',
  DeveloperBoardOutlined: 'Cpu',
  CodeOutlined: 'Code',
  Extension: 'Puzzle',
  ExtensionOutlined: 'Puzzle',
  DeviceHubOutlined: 'Hub',
  HubOutlined: 'Hub',
  PrecisionManufacturingOutlined: 'Bot',
  BiotechOutlined: 'Microscope',
  BugReportOutlined: 'Bug',

  // Time & scheduling
  DateRangeOutlined: 'Calendar',
  CalendarToday: 'Calendar',
  EventRepeatOutlined: 'CalendarRepeat',
  Schedule: 'Clock',
  HistoryOutlined: 'History',
  HourglassEmpty: 'Hourglass',
  AlarmOnOutlined: 'AlarmClock',
  Timer: 'Timer',
  AutoModeOutlined: 'RefreshCw',

  // Media
  PlayArrowOutlined: 'Play',
  PlayCircleOutlined: 'PlayCircle',
  PauseOutlined: 'Pause',
  ImageOutlined: 'Image',
  BrushOutlined: 'Brush',
  ColorLens: 'Palette',
  FormatShapesOutlined: 'Shapes',

  // Layout & views
  ViewListOutlined: 'List',
  ViewModuleOutlined: 'LayoutGrid',
  ViewColumnOutlined: 'Columns3',
  ViewQuiltOutlined: 'LayoutPanelTop',
  BackupTableOutlined: 'Table',
  AspectRatioOutlined: 'Maximize2',

  // Social & misc
  Star: 'Star',
  StarBorder: 'Star',
  ThumbsUpDownOutlined: 'ThumbsUp',
  FlagOutlined: 'Flag',
  RocketLaunchOutlined: 'Rocket',
  ExploreOutlined: 'Compass',
  RadarOutlined: 'Radar',
  TrackChangesOutlined: 'Target',
  TroubleshootOutlined: 'Stethoscope',
  RouteOutlined: 'Route',
  MapOutlined: 'Map',
  LayersClearOutlined: 'Layers',
  PolylineOutlined: 'Spline',

  // Domain / business
  Domain: 'Building2',
  AccountBalanceOutlined: 'Landmark',
  WorkOutline: 'Briefcase',
  AssignmentOutlined: 'ClipboardList',
  NewspaperOutlined: 'Newspaper',
  LocalOfferOutlined: 'Tag',

  // Links
  LinkOutlined: 'Link',
  LinkOff: 'Unlink',
  LinkOffOutlined: 'Unlink',
  OpenInNew: 'ExternalLink',
  OpenInNewOutlined: 'ExternalLink',
  OpenInBrowserOutlined: 'ExternalLink',

  // Shapes
  HorizontalRule: 'Minus',
  CircleOutlined: 'Circle',
  RadioButtonUnchecked: 'Circle',

  // Misc
  AbcOutlined: 'Type',
  ArchitectureOutlined: 'Compass',
  AssistantOutlined: 'Sparkles',
  CenterFocusStrongOutlined: 'Crosshair',
  DifferenceOutlined: 'GitCompare',
  DriveFileRenameOutlineOutlined: 'PencilLine',
  LoupeOutlined: 'CirclePlus',
  ReadMoreOutlined: 'BookOpen',
  ShortTextOutlined: 'AlignLeft',
  SpeakerNotesOutlined: 'StickyNote',
  Stream: 'Radio',
  StreamOutlined: 'Radio',
  SwipeDown: 'ArrowDown',
  SwipeUp: 'ArrowUp',
  SwipeVertical: 'MoveVertical',
  UnpublishedOutlined: 'CircleX',

  // Graph
  GraphOutline: 'Network',
  FamilyTree: 'Network',
  HexagonMultipleOutline: 'Hexagon',
  HexagonOutline: 'Hexagon',
  VectorLink: 'Link2',
  VectorPolygon: 'Pentagon',
  VectorRadius: 'CircleDashed',
};

// ── MDI mdi-material-ui → Lucide ──────────────────────────────────
export const mdiToLucide: Record<string, string> = {
  AccessPoint: 'Wifi',
  AccountGroupOutline: 'Users',
  AutoFix: 'Wand2',
  BankMinus: 'Building2',
  BankPlus: 'Building2',
  BellCogOutline: 'BellCog',
  BellOutline: 'Bell',
  BellPlusOutline: 'BellPlus',
  BellRemoveOutline: 'BellMinus',
  CalendarMultiselectOutline: 'CalendarDays',
  ChartTimeline: 'ChartLine',
  Close: 'X',
  CloudRefreshOutline: 'CloudRefresh',
  CogOutline: 'Cog',
  ContentCopy: 'Copy',
  Database: 'Database',
  DatabaseExportOutline: 'DatabaseBackup',
  DatabaseImportOutline: 'DatabaseBackup',
  DatabaseOutline: 'Database',
  Delete: 'Trash2',
  DotsHorizontalCircleOutline: 'MoreHorizontal',
  FileDelimitedOutline: 'FileText',
  FileExportOutline: 'FileOutput',
  FileOutline: 'File',
  FilePdfBox: 'FileText',
  FileTableBoxMultipleOutline: 'Files',
  FlaskOutline: 'FlaskConical',
  FormatListGroup: 'List',
  GlobeModel: 'Globe',
  GraphOutline: 'Network',
  Group: 'Users',
  HexagonMultipleOutline: 'Hexagon',
  HexagonOutline: 'Hexagon',
  InformationOutline: 'Info',
  KeyOutline: 'Key',
  Label: 'Tag',
  LabelOutline: 'Tag',
  LanguageHtml5: 'Code',
  LanguageMarkdownOutline: 'FileCode',
  Launch: 'ExternalLink',
  LinkVariantPlus: 'Link2Plus',
  LinkVariantRemove: 'Link2Off',
  LockPattern: 'Lock',
  Merge: 'GitMerge',
  NoteTextOutline: 'StickyNote',
  OpenInNew: 'ExternalLink',
  PostOutline: 'FileText',
  ProgressUpload: 'Upload',
  ProgressWrench: 'Wrench',
  RayEndArrow: 'ArrowRight',
  RayStartArrow: 'ArrowRight',
  React: 'Atom',
  RelationManyToMany: 'Link2',
  RssBox: 'Rss',
  SelectAll: 'CheckSquare',
  SelectGroup: 'Boxes',
  SelectionDrag: 'MousePointerSquare',
  Send: 'Send',
  SendOutline: 'Send',
  ShieldCheckOutline: 'ShieldCheck',
  ShieldSearch: 'ShieldSearch',
  SubdirectoryArrowRight: 'CornerDownRight',
  VectorLink: 'Link2',
  VectorPolygon: 'Pentagon',
  VectorRadius: 'CircleDashed',
  Video3d: 'Video',
};
